-- Generated by Assembly-CSharp-Editor Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "TestClassDeclaration"
    },
    types = {
      "Script.CSharpToLua.Editor.input.TestClassDeclaration",
      "Script.CSharpToLua.Editor.input.TestClassDeclaration.A",
      "Script.CSharpToLua.Editor.input.TestClassDeclaration.A.B"
    }
  })
end
