-- Generated by Assembly-CSharp-Editor Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "TestAmonymousObject",
      "TestClassDeclaration",
      "TestDelegateDeclaration",
      "TestExtensionMethod",
      "TestField",
      "TestGenericClass",
      "TestGenericMethod",
      "TestIndexer",
      "TestLambda",
      "TestLifeMethod",
      "TestMethodDeclaration",
      "TestPartialClass",
      "TestProperty"
    },
    types = {
      "Script.CSharpToLua.Editor.input.TestClassDeclaration",
      "Script.CSharpToLua.Editor.input.TestClassDeclaration.A",
      "Script.CSharpToLua.Editor.input.TestGenericClass",
      "Script.CSharpToLua.Editor.input.TestPartialClass",
      "Script.CSharpToLua.Editor.input.MyClass",
      "Script.CSharpToLua.Editor.input.Person",
      "Script.CSharpToLua.Editor.input.Program",
      "Script.CSharpToLua.Editor.input.Test",
      "Script.CSharpToLua.Editor.input.TestAmonymousObject",
      "Script.CSharpToLua.Editor.input.TestClassDeclaration.A.B",
      "Script.CSharpToLua.Editor.input.TestExtensionMethod",
      "Script.CSharpToLua.Editor.input.TestExtensionMethodString",
      "Script.CSharpToLua.Editor.input.TestField",
      "Script.CSharpToLua.Editor.input.TestGenericClass.Test",
      "Script.CSharpToLua.Editor.input.TestGenericClass.Test_2",
      "Script.CSharpToLua.Editor.input.TestGenericMethod",
      "Script.CSharpToLua.Editor.input.TestIndexer",
      "Script.CSharpToLua.Editor.input.TestLambda",
      "Script.CSharpToLua.Editor.input.TestLifeMethod",
      "Script.CSharpToLua.Editor.input.TestPartialClass.PartialA",
      "Script.CSharpToLua.Editor.input.TestProperty"
    },
    Main = "Script.CSharpToLua.Editor.input.Program.Main"
  })
end
