-- Generated by Assembly-CSharp-Editor Compiler
local System = System
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestPartialClass", function (namespace)
    namespace.class("PartialA", function (namespace)
      return {
        b = 2,
        a = 1
      }
    end)
    return {}
  end)
end)
