-- Generated by Assembly-CSharp-Editor Compiler
local System = System
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestGenericClass", function (namespace)
    namespace.class("Test", function (namespace)
      return {}
    end)
    namespace.class("Test_2", function (namespace)
      return function (T, U)
        return {}
      end
    end)
    return {}
  end)
end)
