-- Generated by Assembly-CSharp-Editor Compiler
local System = System
local Scriptinput
System.import(function (out)
  Scriptinput = Script.CSharpToLua.Editor.input
end)
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestExtensionMethod", function (namespace)
    local Reverse
    Reverse = function (str)
      local charArray = str:ToCharArray()
      System.Array.Reverse(charArray)
      return System.String(charArray)
    end
    return {
      Reverse = Reverse
    }
  end)

  namespace.class("TestExtensionMethodString", function (namespace)
    local Test
    Test = function (this)
      local originalString = "Hello World"
      local reversedString = Scriptinput.TestExtensionMethod.Reverse(originalString)
    end
    return {}
  end)
end)
