-- Generated by Assembly-CSharp-Editor Compiler
local System = System
local ArrayInt32 = System.Array(System.Int32)
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestIndexer", function (namespace)
    local get, set, __ctor__
    __ctor__ = function (this)
      this.array = ArrayInt32(10)
    end
    get = function (this, index)
      return this.array:get(index)
    end
    set = function (this, index, value)
      this.array:set(index, value)
    end
    return {
      get = get,
      set = set,
      __ctor__ = __ctor__
    }
  end)
end)
