-- Generated by Assembly-CSharp-Editor Compiler
local System = System
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestGenericMethod", function (namespace)
    local Test, TestDo
    Test = function (this, t, T)
      return t
    end
    TestDo = function (this)
      Test(this, 5, System.Int32)
    end
    return {
      Test = Test,
      TestDo = TestDo
    }
  end)
end)
