-- Generated by Assembly-CSharp-Editor Compiler
local System = System
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestClassDeclaration", function (namespace)
    namespace.class("A", function (namespace)
      namespace.class("B", function (namespace)
        return {}
      end)
      return {}
    end)
    return {}
  end)
end)
