-- Generated by Assembly-CSharp-Editor Compiler
local System = System
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestAmonymousObject", function (namespace)
    local test
    test = function (this)
      local a = System.AnonymousType({
        Name = "a",
        Age = 1
      })
    end
    return {}
  end)
end)
