-- Generated by Assembly-CSharp-Editor Compiler
local System = System
local ListInt32 = System.List(System.Int32)
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestLambda", function (namespace)
    local Test
    Test = function (this)
      local default = ListInt32()
      default:Add(1)
      default:Add(2)
      default:Add(3)
      default:Add(4)
      default:Add(5)
      local numbers = default

      -- simple lambda expression
      numbers:ForEach(function (n)
        System.Console.WriteLine(n)
      end)

      -- Parenthesized Lambda Expression
      numbers:ForEach(function (n)
        System.Console.WriteLine(n)
      end)
      numbers:ForEach(function (n)
        System.Console.WriteLine(n)
      end)

      -- Anonymous Method Expression
      numbers:ForEach(function (n)
        System.Console.WriteLine(n)
      end)
    end
    return {}
  end)
end)
