-- Generated by Assembly-CSharp-Editor Compiler
local System = System
local UnityEngine = UnityEngine
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestLifeMethod", function (namespace)
    local __gc, __ctor1__, __ctor2__
    __ctor1__ = function (this)
      UnityEngine.Debug.Log("构造函数")
    end
    __ctor2__ = function (this, str)
      __ctor1__(this)
    end
    __gc = function (this)
      UnityEngine.Debug.Log("析构函数")
    end
    return {
      __gc = __gc,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
  end)
end)
