-- Generated by Assembly-CSharp-Editor Compiler
local System = System
System.namespace("Script.CSharpToLua.Editor.input", function (namespace)
  namespace.class("TestField", function (namespace)
    local hello, Test
    hello = "hellohellohellohellohellohellohellohellohellohelhellohellohellohellohellohellohellolohellohellohellohellohellohellohellohellohellohello"
    Test = function (this)
      local ss = hello
      local b = 1 --[[TestField.a]]
    end
    return {}
  end)
end)
